### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LaoshuBaby** [moehanabi/tg-reviewer-bot#1]
- [x] 全局投稿ID，可用于主动撤回 [传送门](https://t.me/c/2013668713/1073)
- [x] 传入格式可视为 markdown 并可自动做剧透遮罩 [传送门](https://t.me/c/2013668713/834)
- [x] 封禁投稿 [传送门](https://t.me/c/2013668713/1153)
- [x] 向投稿机器人发送如`/info`/`myinfo`等指令可查看自己过往投稿拒稿通过已审总数及百分比 [传送门](https://t.me/c/2013668713/1285)
- [x] 对审稿与其他人长期不一致情况统计（因政策可能具有变化性故只计算三个月内） [传送门](https://t.me/c/2013668713/1325)
- [x] 保证转发来源的可见与不可见正确展示与处理嵌套转发等问题 [传送门](https://t.me/c/2013668713/2103)
- [x] NSFW通过自动加遮罩，正常通过明确注明是SFW通过，存在任何一个NSFW通过即为NSFW [传送门](https://t.me/c/2013668713/2069)
- [x] 意见不一致程度和一年内活跃度（如连续半年沉寂无操作等）可作为除权标准 [传送门](https://t.me/c/2013668713/1638)
- [ ] 考虑施行“打捞请求（0/2n+1）”，n为通过或拒绝需要的人数。也可写死3或4人即可。可根据 `#REJECT` 查询 [传送门](https://t.me/c/2013668713/2280)、[传送门](https://t.me/c/2013668713/2258)
- [ ] 允许NSFW和SFW自动向两个不同频道转发（可能需要构建iostream之类的抽象） [传送门](https://t.me/c/2013668713/2198)
- [ ] 提供与TG等价的网页版，以API的形式暴露 [传送门](https://t.me/c/2013668713/2338)
- [x] 转发自动开启投稿流程，不一定需要`/new`或者`/start` [传送门](https://t.me/c/2013668713/2357)
- [x] Sticker 投稿
- ~~允许所有审核均提供拒稿理由和在定局前即预填写审核理由（多条会向用户发送多次）(各个功能是否开启可见环境变量，可以关闭以避免暗示有人已审核过) [传送门](https://t.me/c/2013668713/2170)~~
- ~~所有关键字如`/new`或者`/start`均可自定义 [传送门](https://t.me/c/2013668713/2358)~~
- ~~对投稿质量高低的反馈投票（也可看reaction，但易陷入乌合之众困境） [传送门](https://t.me/c/2013668713/1157)~~
- ~~加入自动查重并播报可能于多少日前来到群内，需爬取过往消息建立初始数据库 [传送门](https://t.me/c/2013668713/2261)~~
